Feature/cin 000 sonarqube
Architect-Coders/Equipo5 pull request #16
Opened 2019-11-30 10:55 UTC by adrianlazaro8

## Nombre del branch:
feature/CIN-000_Sonarqube

## Descripcion
La idea era integrar Sonarqube junto a Jacoco y Detekt, pero intentando integrar cada parte por su lado se resistía. Buscando alternativas, encontré una que me parece brutal y además se simplifica mucho la faena: AndroidAnalyzer (https://github.com/pinchbv/android-analyzer).

Es un plugin para Gradle que facilita mucho la vida a la hora de hacer esta integración.

De momento todo se sincroniza de forma manual, pero conforme vaya sacando ratitos investigaré como podemos automatizar esta tarea. 

## Pull request checklist:
- [ ] **El codigo incluye Unit Test**
- [x] **El codigo compila almenos 2 veces antes de crear este pull request**
- [ ] **He realizado cambios en la wiki si es necesario**
- [ ] **El codigo incluido puede romper la app**
- [x] **has avisado al equipo en Slack sobre el Pull Request**

2019-11-30 11:17 UTC, davthecodercom requested changes

2019-11-30 11:17 UTC, DavidCruzUK commented on build.gradle
> +        classpath "com.justpinch:androidanalyzer:1.1.1"
Mueve esta linia a `dependencies.gradle` dentro del array `classpathDependencies` y separa la version en una variable aparte como los demas valores. :)

2019-11-30 11:48 UTC, adrianlazaro8 commented on build.gradle
> +        classpath "com.justpinch:androidanalyzer:1.1.1"
hecho!

2019-11-30 21:13 UTC, soygabimoreno approved these changes

2019-12-15 11:50 UTC, davthecodercom approved these changes

2020-01-07 21:27 UTC, adrianlazaro8 commented
@Architect-Coders/grupo5 os comento cositas:

- Esta rama está actualizada en base a develop
- He hecho un test unitario de prueba y lo ha cogido perfecto =)
- Después de duras batallas, por fin Vodafone me ha actualizado el firmware del router y la apertura de puertos ya funciona, por lo que ya os puedo pasar mi ip y podréis ver el dashboard de Sonarqube que por supuesto no nos va a ayudar demasiado siendo el proyecto tan chiquitín, pero bueno, por si queremos curiosear más que nada :).

¡Si dais el visto bueno mergeamos!

2020-01-07 21:46 UTC, soygabimoreno approved these changes

2020-01-07 21:47 UTC, soygabimoreno commented
De cine!!!

2020-01-11 11:49 UTC, merged