Feature/splash screen
Architect-Coders/Equipo5 pull request #19
Opened 2019-12-01 10:43 UTC by adrianlazaro8

## Nombre del branch:
feature/splash_screen

## Descripcion

- Implementación de una Splash Screen sin activity propia para ello. Utiliza un drawable para sobreescribir el windowBackground de la MainActivity.
- Se ha añadido la font-family Copperplate.

## Pull request checklist:
- [ ] **El codigo incluye Unit Test**
- [X] **El codigo compila almenos 2 veces antes de crear este pull request**
- [ ] **He realizado cambios en la wiki si es necesario**
- [ ] **El codigo incluido puede romper la app**
- [X] **has avisado al equipo en Slack sobre el Pull Request**

2019-12-01 11:02 UTC, davthecodercom requested changes

2019-12-01 11:02 UTC, DavidCruzUK commented on app/src/main/res/drawable/splash_screen.xml
> +    <item android:drawable="@android:color/white" />
el background es `#8D8D8D`

2019-12-01 20:10 UTC, adrianlazaro8 commented on app/src/main/res/drawable/splash_screen.xml
> +    <item android:drawable="@android:color/white" />
toda la razón, ya está modificado

2019-12-06 12:19 UTC, davthecodercom approved these changes

2019-12-07 22:44 UTC, soygabimoreno approved these changes

2019-12-08 22:24 UTC, merged