[implementation] refactoring layers - viewmodel and repository
Architect-Coders/Equipo5 pull request #26
Opened 2019-12-16 14:41 UTC by gabrielpozo

## Nombre del branch:
feature/refactoring-presenter
## Descripcion
- Refactored Presenter for ViewModel and adding repository class to the data layer
- Changed MainActivity implementation to fit with the new ViewModel class
- Added API-key on build config(data layer) so we can retrieve it directly from ApiService class
- Added dependencies to the correspondent class

## Pull request checklist: 
"zzz" package is still on the project in order to compare it with the new implementation

2019-12-16 14:52 UTC, gabrielpozo commented on presentation/build.gradle
> +  //  implementation project(':domain')
he comentado esta linea porque de momento no estamos usando esta capa(domain), y conectamos directamente con data layer(donde esta el repositorio). Mas adelante cuando añadamos casos de uso, tendremos q descomentarla y apuntar unicamente a domain y a su vez domain apuntara a data

2019-12-16 20:28 UTC, adrianlazaro8 approved these changes

2019-12-17 05:53 UTC, soygabimoreno requested changes

2019-12-17 05:53 UTC, GabrielMorenoIbarra commented on app/build.gradle
> -    properties.load(project.file('../local.properties').newDataInputStream())
Esto hará falta para recoger el API KEY de local.properties, ¿no?

2019-12-17 05:53 UTC, GabrielMorenoIbarra commented on app/build.gradle
> -        resValue "string", "movie_db_api_key", properties.getProperty("MOVIE_DB_API_KEY", "")
Al igual que esto.

2019-12-17 05:53 UTC, GabrielMorenoIbarra commented on app/src/main/java/com/architectcoders/equipocinco/di/modules/ApplicationModule.kt
>   */
Esto ya lo comenté en otra PR (pero no lo encuentro). Este tipo de headers, IMHO, aportan menos de lo que quitan, legibilidad. Y siempre tenemos las annotations que son mucho más específicas a nivel de línea para saber quien ha comitteado una cosa u otra.

2019-12-17 05:53 UTC, GabrielMorenoIbarra commented on app/src/main/java/com/architectcoders/equipocinco/di/modules/ApplicationModule.kt
>   */
Si no recuerdo mal, lo mete por defecto y éste es el sitio para cambiarlo:
![Screenshot_20191217_064600](https://user-images.githubusercontent.com/1880789/70968289-08538d80-2099-11ea-8757-99f20f141e0c.png)

2019-12-17 05:53 UTC, GabrielMorenoIbarra commented on app/src/main/java/com/architectcoders/equipocinco/ui/MainActivity.kt
> +    @Inject
¿`@Inject` se podía quitar?

2019-12-17 05:53 UTC, GabrielMorenoIbarra commented on data/build.gradle
> +        buildConfigField "String", "movie_db_api_key", MOVIE_DB_API_KEY
Habrá que aplicar aquí seguramente lo que comentaba en el  `build.gradle` del modulo `:app`.

2019-12-17 10:03 UTC, gabrielpozo commented on app/build.gradle
> -    properties.load(project.file('../local.properties').newDataInputStream())
se me olvido comentar esto. Vi que tenemos este codigo ya en el file de dependencies.gradle entonces creo no hay razon para duplicarlo en el  app/build.gradle tambien

2019-12-17 10:09 UTC, gabrielpozo commented on app/build.gradle
> -        resValue "string", "movie_db_api_key", properties.getProperty("MOVIE_DB_API_KEY", "")
cierto pero ahora obtengo la api_key directamente desde ApiService class usando  "buildConfigField "String", "google_api_key", google_api_key" en data/build.gradle, entonces no hace falta usar el resValue ya mas, y a asi evitamos pasar la api_key por constructor. Creo q es una forma mas segura de hacerlo y limpia pero tambien lo q vosotros opineis

2019-12-17 10:09 UTC, gabrielpozo commented on app/src/main/java/com/architectcoders/equipocinco/di/modules/ApplicationModule.kt
>   */
totalmente de acuerdo Gabi, lo quito para la proxima update de la PR

2019-12-17 10:12 UTC, gabrielpozo commented on app/src/main/java/com/architectcoders/equipocinco/ui/MainActivity.kt
> +    @Inject
me salta una excepcion si quito @inject, entonces creo q seria mejor dejarlo hasta q entremos en el modulo de inyeccion de dependencias y lo refactorizamos de manera como lo tenga Antonio, no creo q haya que cambiar muchas lineas de todas maneras

2019-12-17 10:14 UTC, gabrielpozo commented on data/build.gradle
> +        buildConfigField "String", "movie_db_api_key", MOVIE_DB_API_KEY
claro, como ya comentaba antes, en el app/build.gradle No nos hace falta ya porque el api_key la recogemos desde ApiService class, que esta en la capa/modulo de data

2019-12-17 20:03 UTC, GabrielMorenoIbarra commented on app/build.gradle
> -    properties.load(project.file('../local.properties').newDataInputStream())
Ah, valeee... no me había dado cuenta. Genial!

2019-12-17 20:03 UTC, GabrielMorenoIbarra commented on app/build.gradle
> -        resValue "string", "movie_db_api_key", properties.getProperty("MOVIE_DB_API_KEY", "")
De cine!

2019-12-17 20:04 UTC, GabrielMorenoIbarra commented on app/src/main/java/com/architectcoders/equipocinco/di/modules/ApplicationModule.kt
>   */
Chachi!

2019-12-17 20:04 UTC, GabrielMorenoIbarra commented on data/build.gradle
> +        buildConfigField "String", "movie_db_api_key", MOVIE_DB_API_KEY
Está clar. De pm!

2019-12-17 20:04 UTC, soygabimoreno approved these changes

2019-12-18 10:11 UTC, gabrielpozo commented on app/build.gradle
> +        resValue "string", "movie_db_api_key", MOVIE_DB_API_KEY
una vez quitemos el paquete zzz, tendremos que quitar esta linea porque ya nos es inutil

2019-12-22 11:21 UTC, merged