Navegación entre master y detail
Architect-Coders/Equipo5 pull request #37
Opened 2020-01-01 19:25 UTC by adrianlazaro8

## Nombre del branch:
feature/5_navigation_mater_to_detail

## Descripcion
Se ha implementado la navegación entre master y detail. Como existen issues diferentes, de momento la navegación se hace sin safeargs, y pasando el objeto movie entero.

## Pull request checklist:
- [ ] **El codigo incluye Unit Test**
- [X] **El codigo compila almenos 2 veces antes de crear este pull request**
- [X] **He realizado cambios en la wiki si es necesario**
- [ ] **El codigo incluido puede romper la app**
- [X] **has avisado al equipo en Slack sobre el Pull Request**

2020-01-01 19:55 UTC, soygabimoreno requested changes

2020-01-01 19:55 UTC, soygabimoreno commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" project-jdk-name="1.8" project-jdk-type="JavaSDK">
Este fichero no debería ir dentro de VCS, ¿no?

2020-01-01 21:16 UTC, adrianlazaro8 commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" project-jdk-name="1.8" project-jdk-type="JavaSDK">
Lo tengo en cuenta para el próximo PR y actualizo el .gitignore, que efectivamente también entiendo que no se debería trackear este fichero.

Gracias!

2020-01-02 06:22 UTC, soygabimoreno commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" project-jdk-name="1.8" project-jdk-type="JavaSDK">
Claro. Haz otro commit en esta PR directamente mejor :blush:

2020-01-02 06:25 UTC, DavidCruzUK commented
Chicos, creo que esto esta tarea esta 2 veces, porque la empece a hacer yo en la tarea 6

2020-01-02 06:35 UTC, soygabimoreno commented
Ya... creo que la confusión ha venido porque pensábamos que ibas a hacer únicamente la pantalla de detalle y no la navegación

2020-01-02 07:13 UTC, DavidCruzUK commented
entiendo, pero la navigacion por si sola seria una tarea bastante corta, al igual que es solo la interfaz.
vista detalle es todo y no hace falta 2 tickets para esto

2020-01-02 17:34 UTC, DavidCruzUK commented
Cambios mergeados con en  el PR: #38

2020-01-02 17:34 UTC, closed without merging