Películas populares basándose en la ubicación del usuario
Architect-Coders/Equipo5 pull request #53
Opened 2020-01-18 16:44 UTC by adrianlazaro8

## Nombre del branch:
feature/48_geolocation

## Descripcion
Se ha implementado la obtención de las películas populares en base a la ubicación del usuario.

## Pull request checklist:
- [ ] **El codigo incluye Unit Test**
- [X] **El codigo compila almenos 2 veces antes de crear este pull request**
- [X] **He realizado cambios en la wiki si es necesario**
- [ ] **El codigo incluido puede romper la app**
- [X] **has avisado al equipo en Slack sobre el Pull Request**

2020-01-18 16:47 UTC, soygabimoreno approved these changes

2020-01-18 17:02 UTC, davthecodercom approved these changes
Genial!

2020-01-19 16:27 UTC, gabrielpozo approved these changes

2020-01-19 16:27 UTC, gabrielpozo commented on app/src/main/java/com/architectcoders/equipocinco/data/PlayServicesLocationDataSource.kt
> +    private val geocoder = Geocoder(application)
Geocoder deberia ser inyectado en el constructor y creado en el modulo de dagger en vez de crearlo en la clase misma. Si se crea en la clase misma no es posible mockearlo despues a la hora de hacer el testing. A parte haciendolo asi, no estas escondiendo como se construye este objeto y se algun dia tienes que cambiar las dependencias de este objeto, tendras q cambiarla en cada uno de los sitios donde este se llame o incluso si se llama. o Tambien si cambias el objeto q implementa esa interfaz aunque en este caso GeoCoder es un objeto plano normal q no referencia a un interfaz)

2020-01-19 16:27 UTC, gabrielpozo commented on app/src/main/java/com/architectcoders/equipocinco/data/PlayServicesLocationDataSource.kt
> +    private val fusedLocationClient = LocationServices.getFusedLocationProviderClient(application)
Lo mismo aqui

2020-01-19 16:29 UTC, davthecodercom requested changes
@adrianlazaro8 dale un vistazo a los comentarios de @gabrielpozo

2020-01-19 16:31 UTC, davthecodercom approved these changes

2020-01-20 18:15 UTC, merged