Get movie from singleSourceOfData and display to DetailMovieFragmetn
Architect-Coders/Equipo5 pull request #55
Opened 2020-01-19 15:44 UTC by DavidCruzUK

Porfavor, incluye este checklist basico para validar el pull request.

## Nombre del branch:
origin/feature/#35_Pass-id-value-between-Master-and-Detail-Fragments

## Descripcion
Pass ID from MovieFragment to DetailFragment and use it with the SingleSourceOfData implemented by @gabrielpozo using same structure to get the movie and display in to DetailMovieFragment

## Pull request checklist:
- [ ] **El codigo incluye Unit Test**
- [x] **El codigo compila almenos 2 veces antes de crear este pull request**
- [ ] **He realizado cambios en la wiki si es necesario**
- [ ] **El codigo incluido puede romper la app**
- [X] **has avisado al equipo en Slack sobre el Pull Request**

2020-01-19 16:54 UTC, gabrielpozo requested changes

2020-01-19 16:54 UTC, gabrielpozo commented on presentation/src/main/java/com/architectcoders/presentation/viewmodels/DetailMovieViewModel.kt
> +    private fun handleGetMovieByIdResponse(dataState: DataState<Movie>) {
es una tonteria pero yo pondria handleMovieByIdResponse el nombre del metodo, handleGetMovieByIdResponse parece q esta haciendo un poco de referencia al Repositorio pero ya te digo es un tonteria muy grande

2020-01-19 16:54 UTC, gabrielpozo commented on data/src/main/java/com/architectcoders/data/ApiRepo.kt
> +        networkCall = { remoteDataSource.fetchMovies() },
por consecuente tienes que crear otro metodo en el localDatasource, rollo localDataSource.saveMovie o localDataSource.saveMovieById

2020-01-19 16:54 UTC, gabrielpozo commented on data/src/main/java/com/architectcoders/data/ApiRepo.kt
> +        networkCall = { remoteDataSource.fetchMovies() },
remoteDataSource.fetchMovies()me parece redundante, lo mejor seria crear otro metodo en el RemoteDataSource class tal como asi: remoteDataSource.fetchMovieById() y añadir una llamada a la Api q solo te traiga esa pelicula, ya q traerte todo el bloque de Movies de la api otra vez no es lo mas eficiente.

2020-01-19 16:55 UTC, DavidCruzUK commented on presentation/src/main/java/com/architectcoders/presentation/viewmodels/DetailMovieViewModel.kt
> +    private fun handleGetMovieByIdResponse(dataState: DataState<Movie>) {
hecho

2020-01-19 16:56 UTC, DavidCruzUK commented on data/src/main/java/com/architectcoders/data/ApiRepo.kt
> +        networkCall = { remoteDataSource.fetchMovies() },
tienes razon, lo cambio

2020-01-19 17:10 UTC, DavidCruzUK commented on data/src/main/java/com/architectcoders/data/ApiRepo.kt
> +        networkCall = { remoteDataSource.fetchMovies() },
done

2020-01-19 17:11 UTC, DavidCruzUK commented on data/src/main/java/com/architectcoders/data/ApiRepo.kt
> +        networkCall = { remoteDataSource.fetchMovies() },
lo he cambiado como hemos hablado en slack. reduciendo la overingenieria

2020-01-19 17:42 UTC, gabrielpozo approved these changes

2020-01-19 21:15 UTC, soygabimoreno approved these changes

2020-01-20 18:17 UTC, adrianlazaro8 approved these changes

2020-01-21 21:13 UTC, soygabimoreno approved these changes

2020-01-21 21:17 UTC, merged